[package]
name = "tts-server"
version = "0.2.1"
authors = ["litcc"]
edition = "2021"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.5", features = ["derive"] }  # 命令行解析库
num_cpus = "1.13.1"  # 获取cpu信息
itertools = "0.10.3"  # 迭代器工具库
fancy-regex = "0.10.0"  # 正则库
log = "0.4.17"  # 日志库
log4rs = "1.1.1"  # 日志扩展库
env_logger = "0.9.0"  # 日志扩展库
num = "0.4.0"  #计算库
uuid = { version = "0.8.2", features = ["v4"] }  # uuid库
urlencoding = "2.1.0"  # url编码解析库
rand = "0.8.5"  # 随机数库
futures-util = "0.3.21"  # 异步工具库
reqwest = { version = "0.11.11", features = ["json", "native-tls"] }  # http 请求库
once_cell = "1.12.0"
bytes = "1.1.0"
serde = "1.0.137"
serde_json = "1.0.81"
bincode = "1.3.3"
actix-web = "4.1.0"
actix-rt = "2.7.0"
local_ipaddress = "0.1.3"  # 获取本地ip
tokio-native-tls = "0.3.0"
## tokio-tungstenite 暂时不能升级，可能是库有问题了，或者是我用法出问题了，暂时没有分析
tokio-tungstenite = { version = "0.17.1", features = ["native-tls"] }
tokio = { version = "1.19.2", features = ["full"] } # 协程库
rust-embed = "6.4.0"  # 嵌入文件库
mime_guess = "2.0.4"  # 文件类型检测
event_bus = { git = "https://github.com/litcc/event_bus.git" }
chrono = "0.4.19" # 时间库

[profile.release]
opt-level = 'z'
#lto = true
#codegen-units = 1
panic = 'abort'